name: Happy ECC - Revenge
author: Giapppp
public: true
flag: idek{find_the_order_of_hyperelliptic_curve_is_soooo_hard_if_its_not_zero:((_75f492115a34ff4324212e09e24aa5bd}
description: |-
  This curve is happy because it knows it's not an elliptic curve !
  The password to decrypt is the flag of challenge `Happy ECC`