version: '3.9'

services:
  api:
    build:
      context: ./backend
    ports:
      - "5000"
    env_file: ".env"
    environment:
      - NODE_ENV=production
    

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
