name: Sadness ECC
author: Giapppp
public: true
flag: idek{the_idea_came_from_a_Vietnamese_high_school_Mathematical_Olympiad_competition_xD}
description: This curve is sad because it doesn't know if it's an elliptic curve or not...
