name: Sadness ECC - Revenge
author: Giapppp
public: true
flag: idek{the_idea_came_from_a_Vietnamese_high_school_Mathematical_Olympiad_competition_xD_sorry_for_unintended_:sob:_75f492115a34ff4324212e09e24aa5bd}
description: |-
  This curve is sad because it doesn't know if it's an elliptic curve or not...
  The password to decrypt is the flag of challenge `Sadness ECC`
